### ISSUE TITLE
How do I remove red line in center screen?

### ISSUE THREAD

**Issue by ghost** [journeyapps/zxing-android-embedded#152]

**Comment by rkistner** [comment]
You can use BarcodeView directly, instead of CompoundBarcodeView. This does mean you won't be able to use the IntentIntegrator directly. Look at a sample like this as a starting point:

https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/CustomScannerActivity.java

**Comment by Bajranghudda1** [comment]
@huongta try this
CompoundBarcodeView barcodeView = ...
barcodeView.getViewFinder().setVisibility(View.INVISIBLE);
