### ISSUE TITLE
setScreenOrientation() property for IntentIntegrator

### ISSUE THREAD

**Issue by garenyondem** [journeyapps/zxing-android-embedded#16]
It would be awesome to have a setScreenOrientation method for IntentIntegrator class. I am using the project by including the dependency so i am not allowed to edit any code inside it. If it was available it would be great for gradle projects.

**Comment by KingWu** [comment]
+11

**Comment by markusekblad** [comment]
Also interested in this.

**Comment by rkistner** [comment]
There is an open pull request #18 that implements this. There are however some issues that have to be fixed before it can be merged, I and haven't had the time to look into that yet.

That said, I would caution anyone against using any orientation other than the default landscape. The reason is that many phones simply do not support any orientation other than the default landscape properly. If you use inverse landscape, some phones just render an inverted preview (rotated 180 degrees). On portrait mode, it can get much worse. I've seen weird aspect ratios, completely distorted previews, and crashes. It may work completely fine on your development phones, and then break completely on your users' phones. On some devices it can be fixed by using specific orientation settings. Unfortunately, the firmware on other devices is so broken that I couldn't find any fix.

The last time I did proper testing was around two years ago, so it's possible that the situation has improved since then. It is still not something I would recommend though. And if you do try this, make sure you test it on many different devices.

**Comment by markusekblad** [comment]
Thanks a lot for the info!

**Comment by rkistner** [comment]
Is anyone aware of an existing barcode scanner app that work well in portrait mode (preferably open source)? It would help to have something as a reference. Alternatively a photo app that works in portrait mode could also work.

**Comment by garenyondem** [comment]
[They have it](https://play.google.com/store/apps/details?id=com.inomera.sm&hl=tr) but it's not opensource.

**Comment by rjong** [comment]
Please merge, I want to use it portrait.

**Comment by ouachman** [comment]
I am also very interested in this :)

**Comment by rkistner** [comment]
I created an experimental branch to support orientation changes:

https://github.com/journeyapps/zxing-android-embedded/tree/orientation-support

I would appreciate some testing. You can try it out by following the "Building locally" section of the readme.

To use it, set with orientation with e.g. `integrator.setOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR)`.

**Comment by rjong** [comment]
When will you merge it so we can use it with gradle?

**Comment by carbamide** [comment]
I'm also very interested in this.

**Comment by rkistner** [comment]
This is released in version 2.2.0 now. I haven't tested on many different devices yet, so consider the feature experimental. Please let me know if you find any issues.

**Comment by rkistner** [comment]
v2.2.0 contains an issue that prevented 1D barcodes from scanning, fixed in v2.3.0. See #32 for details.

**Comment by philipstratford** [comment]
I'm using v3.3.0 but I can't see how to specify the orientation when creating the IntentIntegrator intent. Did this feature get removed? My app is definitely suited to a portrait orientation, so it's quite jarring when, upon launching the barcode scanning feature, the device must be rotated.

**Comment by qymspace** [comment]
Has there been any development on this. Did you manage to fix issues and merge?

**Comment by SteveRapp** [comment]
Honestly, just losing the text that shows up on the "bottom" (AKA sideways on the left side of the screen) would be enough of a fix for my (and probably most people's) purposes. It just makes the app look ridiculous and sloppily designed that the entire thing is portrait up until you open the QR reader and it insists on being landscape. Without the text, you wouldn't be able to tell it's gone into landscape. The instructions given by the text are beyond obvious anyway. It could just go away with no real impact on user experience.

**Comment by VuVanLuannd** [comment]
How do I scan the QR code with the front camera?
