### ISSUE TITLE
How to release the scanner camera?

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#191]
I am using scanner camera and after scanning all things i want to close the scanner camera and in another activity i want to take a picture, as i researched i can't take picture using scanner so i need to reopen android's camera app to capture the image.
    The problem is when i go into another activity sometimes camera starts and sometime couldn't. And before to start android's camera for sure i am calling **capture.onPause()** .

So my need is only capture the image after scanning things completed. How i can do this? or i can't use android's camera app with scanner?

**Note** - Its working fine when i am opening camera using camera intent "ACTION_IMAGE_CAPTURE".

**Comment by rkistner** [comment]
The issue here is likely because of the camera being managed (and closed) in a background thread. So by the time you switch to the camera Activity, it may not have been released yet.

We'll need to expose a method to wait for the camera to be released to solve this properly. Until then a workaround could be to repeatedly try to open the camera until it succeeds.

**Comment by rkistner** [comment]
A new method, `BarcodeView#pauseAndWait()` has been added, and is now used by default from `CaptureManager` (in 3.5.0). This waits until the camera has been released by the background thread.
