### ISSUE TITLE
Cannot disable laser red line

### ISSUE THREAD

**Issue by lisitso** [journeyapps/zxing-android-embedded#195]
#### Description of the problem:

It's not properly a bug I know, but I please could indicate how to disable the laser red line? Moreover, is it possible to customize the view (ViewfinderView?) that contains the laser with a drawable background? I integrated the library via gradle 
compile 'com.journeyapps:zxing-android-embedded:3.3.0@aar'
Thanks in advance!

**Which library version are you using?** E.g. 3.2.0.
3.3.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Samsung Galaxy S6 and any other device

**Comment by rkistner** [comment]
You can do this if you write a custom Activity.

You can either override ViewfinderView with custom logic (see #73), or not use it at all - just use BarcodeView directly instead of DecoratedBarcodeView. You can see the source for DecoratedBarcodeView here: https://github.com/journeyapps/zxing-android-embedded/blob/master//zxing-android-embedded/src/com/journeyapps/barcodescanner/DecoratedBarcodeView.java - it doesn't do much more than combining the BarcodeView and ViewfinderView.
