### ISSUE TITLE
Different frequency of finding result points in sample app and using library in personal project

### ISSUE THREAD

**Issue by zoopolitic** [journeyapps/zxing-android-embedded#281]
#### Description of the problem:
When scanning within sample app - it finds qr code pretty fast and result points(yellow) drawing every 80ms (as set in ViewfindingView). When using same code within personal app - it finds qr code not so fast and result points drawing approx. every 1 second. I've tried moving sample app out from project and making it separate project instead of module and in this case points also drawing every 1 sec, not 80 ms. Seems like DecoderThread has some kind of decode frequency, but I didn't find where I can configure it.

**Which library version are you using?** 
3.4.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,  Android 5.0)**
nexus 5, 6.0.1

**Does the same happen on other devices or an emulator?**
Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
the problem is in different behavior while using sample and personal apps.

**In the case of an error do you have a stack trace or adb logs?**
There are not errors

**Comment by rkistner** [comment]
DecoderThread decodes as soon as a frames comes in, then requests another frame. The issue here could either be camera-related (receiving frames from the camera at a slower rate, or different camera parameters), or performance-related (decoding taking longer for some reason).

Unfortunately issues like these are difficult to debug. A few potential causes I can think of:
 * An app-wide theme, e.g. something that adds / changes a toolbar.
 * Target SDK version.
 * Hardware acceleration or OpenGL settings.
 * Something in the app causing slowdown (e.g. a CPU-intensive background service).

You should also confirm that the camera settings is the same in both cases (should be logged to the adb logs).

**Comment by rkistner** [comment]
Need more info to debug.
