### ISSUE TITLE
Mirror mode

### ISSUE THREAD

**Issue by Chesteer89** [journeyapps/zxing-android-embedded#34]
Hi once again,

I'm looking for an idea to mirror BarcodeView. When i'm using facing camera and scanning image on right side Viewfinder looks ok (showing result points in left side), but Surface showing image in right. I need to set some flag to mirror it - I've got some text near qr's which should be visible on photo.

**Comment by rkistner** [comment]
Android mirrors the preview image for the front Camera on the SurfaceView, and I'm not sure if it can be reversed without a lot a trouble (using TextureView).

I know it is currently an issue that the resultpoints don't match up with the SurfaceView, since the image used for decoding is not mirrored. I plan on fixing that at some point, but that will most likely be done in the ViewfinderView.

**Comment by rkistner** [comment]
This is finally fixed in v4.0.2 - the ResultPoints now display in the correct place in a mirrored image.
