### ISSUE TITLE
Can the library read code 39 generated via font for the MS office.

### ISSUE THREAD

**Issue by palVikas9** [journeyapps/zxing-android-embedded#356]
#### Description of the problem:
Hi, while testing the integration of the library with the application, we found that the barcode generated from Free 3 of 9 extended font in MS-office is not getting scanned. 

Are these supported in the library or not, as there are several users who generate barcodes using this method. It will be very helpful if we could scan these also via the scanner library. 

Thanks for such a lovely and easy to integrated library.

**Which library version are you using?** E.g. 3.5.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Moto G4 Plus,
  Android 7.0)**

**Does the same happen on other devices or an emulator?** - Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
Code 39 is supported, and it seems like it's the same as 3 of 9.

Please post an example (e.g. a screenshot) of the barcode that fails to
scan.


On Dec 27, 2017 12:26, "palVikas9" <notifications@github.com> wrote:

Description of the problem:

Hi, while testing the integration of the library with the application, we
found that the barcode generated from Free 3 of 9 extended font in
MS-office is not getting scanned.

Are these supported in the library or not, as there are several users who
generate barcodes using this method. It will be very helpful if we could
scan these also via the scanner library.

Thanks for such a lovely and easy to integrated library.

*Which library version are you using?* E.g. 3.5.0.


*Which phone/tablet are you using, and which Android version does it run?
(e.g. Moto G4 Plus, Android 7.0)*

*Does the same happen on other devices or an emulator?* - Yes


*Can you reproduce the issue in the sample project included with the
library? If not, can you provide your own sample project or sample code
that produces this error?*

*In the case of an error do you have a stack trace or adb logs?*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/journeyapps/zxing-android-embedded/issues/356>, or mute
the thread

**Comment by palVikas9** [comment]
Hi this is the barcode sample in the application. Can you please check and let us know what is the problem in the application.

[Barcode sample.xlsx](https://github.com/journeyapps/zxing-android-embedded/files/1590532/Barcode.sample.xlsx)

**Comment by rkistner** [comment]
I do not have MS Excel or the font on my machine, could you post a screenshot?
