### ISSUE TITLE
IntentIntegrator - multiples requestCode

### ISSUE THREAD

**Issue by grmaciel** [journeyapps/zxing-android-embedded#41]
Hi, i would like to call multiples scan within the same activity. Are there a prevision on provide a way to set the requestCode to the IntentIntegrator myself? 

Thank you,

**Comment by rkistner** [comment]
Instead of calling `integrator.initiateScan()`, you can do the following:

```java
Intent intent = integrator.createScanIntent();
startActivityForResult(intent, MY_REQUEST_CODE);
```

If you do this, you'll have to parse the result yourself. See [IntentIngetator.parseActivityResult()](https://github.com/journeyapps/zxing-android-embedded/blob/cec0bd21025582892fc76b8026396d1660691440/integration/src/main/java/com/google/zxing/integration/android/IntentIntegrator.java#L447-L465) for how it's done.
