### ISSUE TITLE
Whitelisting content of readings?

### ISSUE THREAD

**Issue by misteu** [journeyapps/zxing-android-embedded#435]
#### Description of the problem:
I am using 3.6.0 of the library.
My implementation of zxing-embedded is the following: There is an Activity opening my ScannerActivity via onCreate. The opened scannerActivity has a "DecoratedBarcodeView".

My ScannerActivity is finished as soon as anything is read (which is the standard behavior of zxing as far as I understood).

In my setting there are only a couple of QR-Codes I want to read. So it is a problem if it is able to read everything. The scanner even "reads" my carpet floor when it's focussing long enough :-D

Is there some way to restrict the scanner to a whitelist of contents? Similar to integrator.setDesiredBarcodeFormats()? Something like integrator.setDesiredContents(String[] qrContents)?

Normally, I would check the content myself after scanning. But I don't see how to do it because of the scanner's auto-closing behavior. I do not want to see the initial screen as soon as a valid QR-code is read.

I could put a third activity between the two only for validating but that feels like an unnecessary hack. That solution may also produce graphical issues (flickering) when reloading after scanning an invalid qr-code I could imagine.

**Comment by rkistner** [comment]
In general you shouldn't need this unless you also want to avoid scanning other QR codes. In my experience the QR code scanning is fairly good, and doesn't easily pick up anything else as a barcode. However, you do need to make sure you don't allow any other type of barcode, especially 1D barcodes.

That said, this is possible, but you'll have to go fairly deep into the internals.

## Approach 1 - Custom Reader

You'll essentially need a custom Reader class that filters the barcodes before sending it to the activity. Unfortunately you'll need to add a lot of custom code throughout the stack to achieve this.

To start with, you'll need a custom scan Activity. Use this as a starting point:
https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/CustomScannerActivity.java

Then, you need to set a custom DecoderFactory, as in this example:
https://github.com/journeyapps/zxing-android-embedded/blob/aec45c4f10e3769d7449bcb7b82b5d09689512a4/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java#L64

However, the DefaultDecoderFactory is not sufficient for this use case. You'll have to create a custom one - something like this:

```java
public class FilteredDecoderFactory implements DecoderFactory {
    @Override
    public Decoder createDecoder(Map<DecodeHintType, ?> baseHints) {
        Map<DecodeHintType, Object> hints = new EnumMap<>(DecodeHintType.class);

        hints.putAll(baseHints);

        if(this.hints != null) {
            hints.putAll(this.hints);
        }

        if(this.decodeFormats != null) {
            hints.put(DecodeHintType.POSSIBLE_FORMATS, decodeFormats);
        }

        if (characterSet != null) {
            hints.put(DecodeHintType.CHARACTER_SET, characterSet);
        }

        MultiFormatReader reader = new MultiFormatReader();
        reader.setHints(hints);
        FilteredReader filtered = new FilteredReader(reader);

        switch (scanType) {
            case 0:
                return new Decoder(filtered);
            case 1:
                return new InvertedDecoder(filtered);
            case 2:
                return new MixedDecoder(filtered);
            default:
                return new Decoder(filtered);


        }


    }
}


public class FilteredReader implements Reader {
    private MultiFormatReader reader;

    public FilteredReader(MultiFormatReader reader) {
        this.reader = reader;
    }

    public Result decode(BinaryBitmap image) throws NotFoundException, ChecksumException, FormatException {
        Result result = this.reader.decodeWithState(image);
        if (result == null) {
            return null;
        }

        // filter possible results
        if (result.getText().equals("myvalue")) {
            return result;
        }

        return null;
    }

    public Result decode(BinaryBitmap image, Map<DecodeHintType,?> hints) {
        return this.decode(image);
    }

    public void reset() {
        this.reader.reset();
    }
}

```

Note: I did not test any of this code. If you do get it working, please post any code here, and we can add it to the samples.

## Aproach 2 - Custom Activity

In this approach, you filter out the barcode in the Activity, instead of during the decode process.

Start with this example:

https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

Then in the `BarcodeCallback`, you can add your own filter logic. Then when you do get the barcode you want, stop scanning and return the result to the calling Activity (you'll need your own code for this).

**Comment by misteu** [comment]
Thank you very much for your detailled answer! The first is interesting for future projects but it looks a little bit overkill.

That second approach looks just like what I've been looking for, thank you for that example. Definitely will try that one.
