### ISSUE TITLE
Continuous scan is scanning more than the selected formats

### ISSUE THREAD

**Issue by KredeDK** [journeyapps/zxing-android-embedded#461]
#### Description of the problem:
**Which library version are you using?** 3.6.0
**Nokia 7 plus - Android 9**

When using the continuous scanning activity, the scanner will still scan undesired barcode formats. I.e. the default setting in the file is QR codes and code 39, but the scanner will still scan other barcode formats, like EAN or code 128.
The scanner seems to be ignoring this part of the code:
```
Collection<BarcodeFormat> formats = Arrays.asList(BarcodeFormat.QR_CODE, BarcodeFormat.CODE_39);
        barcodeView.getBarcodeView().setDecoderFactory(new DefaultDecoderFactory(formats));
```

Is there a workaround, where I can scan multiple barcodes, but only the desired formats? When using the normal intents, the desired barcodes works fine. The problem only seems to exist with the continuous reader.

**Comment by rkistner** [comment]
Confirmed this issue in the same app. There the issue seems to be with these lines:

https://github.com/journeyapps/zxing-android-embedded/blob/6556f815584f921e21bb088d2f6423baa99d0547/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java#L63-L65

What happens is that `initializeFromIntent` replaces the DecoderFactory with the default one. Changing the order of those lines should solve the issue.

Is the same happening in your app?

**Comment by KredeDK** [comment]
I swapped line 64 and line 65, and it seems to work as intended now. Thank you very much!
