### ISSUE TITLE
Unrecognized

### ISSUE THREAD

**Issue by sundyliang** [journeyapps/zxing-android-embedded#516]
![image](https://user-images.githubusercontent.com/17984003/70206635-1c2af580-1763-11ea-93df-5ab9c752aba2.png)

**Comment by rkistner** [comment]
Please folllow the issue template. Specifically, does it work with the Barcode Scanner application?

In this case it's probably because the image is slightly warped, which breaks the alignment. Bigger QR codes have an extra identifier square in the bottom-right corner which helps for cases like this.

**Comment by aazamansari58061-ctrl** [comment]
![Image](https://github.com/user-attachments/assets/0544582b-ded9-4d03-a754-61ddf600fd6f)

**Comment by samimaktarmashaldaha-create** [comment]
https://github.com/journeyapps/zxing-android-embedded/issues/516

**Comment by skasim44671-cell** [comment]
6015771Q157136353003006376

**Comment by ganpatsaini7491-a11y** [comment]
Res I'll
