### ISSUE TITLE
Barcode scan image outside of dialog

### ISSUE THREAD

**Issue by WOSHICAIXIANFENG** [journeyapps/zxing-android-embedded#90]
Hi, I use one FragmentDialog to show barcode scanner, but the scan image will be outside of dialog If I set certain values for height & width for CompoundBarcodeView. (I use compoundBarcodeView in my layout).  how to set correct width & height for CompoundBarcodeView to avoid library auto change its preview size. (the library will try to get the best preview size for Camera by settings ) ??

<img width="264" alt="screen shot 2015-10-15 at 10 42 59 am" src="https://cloud.githubusercontent.com/assets/3040790/10503544/a6da83cc-7329-11e5-9700-82d4a38659e9.png">

 compile 'com.journeyapps:zxing-android-embedded:3.0.2@aar'
 compile 'com.google.zxing:core:3.2.0'

How to reproduce ?
1. set Activity to dialog them in samples. 
2. set some certain values for height & width.

**Comment by rkistner** [comment]
This will require using SurfaceTexture instead of SurfaceView. I'll work on that for the next release.

**Comment by rkistner** [comment]
I have an experimental branch (not released yet) that has an option for using TextureView instead of SurfaceView:

https://github.com/journeyapps/zxing-android-embedded/tree/surface-texture

It is not enable by default, but you can specify on the BarcodeView / CompoundBarcodeView:
        
    app:zxing_use_texture_view="true"

Note that it only has an effect on Android API level 14+, on pre-14 devices it will still use the SurfaceView.

It may also have performance implications.

**Comment by commjoen** [comment]
We would really like to be able to use such a feature...

**Comment by gkapusta** [comment]
@rkistner when do you plan to merge these changes to master?

**Comment by rkistner** [comment]
@gkapusta Released in version 3.1.0. It's not the default yet though - I still want to make some tweaks to the preview size calculation.

**Comment by meierjan** [comment]
Thanks works fine.
